# Generated by Django 5.1 on 2024-08-16 22:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('max_lines', models.IntegerField()),
                ('min_bet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('coordinates', models.JSONField()),
                ('slot_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paylines', to='slot.slotmachine')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lines', models.IntegerField()),
                ('total_winnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slot_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.slotmachine')),
            ],
        ),
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_result', models.JSONField()),
                ('winnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spin_time', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.CharField(max_length=100)),
                ('symbol_count', models.IntegerField()),
                ('payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slot_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.slotmachine')),
            ],
        ),
    ]
